name: Instagram Bot Scheduler

on:
  schedule:
    # UTC Times: 4:30 (10 AM IST), 9:30 (3 PM IST), 15:30 (9 PM IST)
    - cron: '30 4,9,15 * * *'
  workflow_dispatch: # Button option

jobs:
  post-reel:
    runs-on: ubuntu-latest
    permissions:
      contents: write # History save karne ke liye zaroori hai
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        # Developer version zaroori hai error fix ke liye
        run: pip install -r requirements.txt

      - name: Run Bot Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DRIVE_SATISFY_ID: ${{ secrets.DRIVE_SATISFY_ID }}
          DRIVE_FUNNY_ID: ${{ secrets.DRIVE_FUNNY_ID }}
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
          INSTA_SESSION: ${{ secrets.INSTA_SESSION }}
        run: python insta_bot.py

      - name: Save Upload History
        run: |
          git config --global user.name "InstaBot"
          git config --global user.email "bot@github.com"
          git pull
          git add history.txt
          git commit -m "Video uploaded & history updated" || echo "No changes"
          git push
